### ISSUE TITLE
invalid obfuscated id case, raise undefined method `%' for true:TrueClass

### ISSUE THREAD

**Issue by yossy-ok** [mguymon/obfuscate#5]
Hi @mguymon, thank you for good gem.

I'm using `find_obfuscated` with `block` mode, but sometimes it raise unhandled exception.
```ruby
User.find_obfuscated(params[:id])
```
```
error: undefined method `%' for true:TrueClass
/usr/local/bundle/gems/otherinbox-crypt19-1.2.1/lib/crypt/blowfish.rb:82:in `block in decrypt_pair'
/usr/local/bundle/gems/otherinbox-crypt19-1.2.1/lib/crypt/blowfish.rb:81:in `downto'
/usr/local/bundle/gems/otherinbox-crypt19-1.2.1/lib/crypt/blowfish.rb:81:in `decrypt_pair'
/usr/local/bundle/gems/otherinbox-crypt19-1.2.1/lib/crypt/blowfish.rb:103:in `decrypt_block'
/usr/local/bundle/gems/obfuscate-0.0.7/lib/obfuscate/crypt.rb:76:in `clarify'
/usr/local/bundle/gems/obfuscate-0.0.7/lib/obfuscate/obfuscatable.rb:77:in `clarify_id'
/usr/local/bundle/gems/obfuscate-0.0.7/lib/obfuscate/obfuscatable.rb:70:in `find_obfuscated'
/app/controllers/users_controller.rb:13:in `show'
```

If id is `414`, it raise unknown error, but if id is `1`, it doesn't (just `ActiveRecord::RecordNotFound`).
Maybe because of invalid base64 string and blowfish block string.

I'm thinking that I should wrap the method everywhere like
```ruby
begin
  User.find_obfuscated(params[:id])
rescue
  raise ActiveRecord::RecordNotFound
end
```

but it's too long.

How to avoid this problem? How do you handle this?
(I think this is not this gem problem, but...)

**Comment by mguymon** [comment]
Do you have an example of an id that causes the error, or even better, a test case that shows the error?

**Comment by yossy-ok** [comment]
Thank you for your reply!
l know only `414`, I don't know other error id case.

I check in rails console again,

```
irb(main):001:0> Obfuscate.setup do |config|
irb(main):002:1*   config.salt = "User"
irb(main):003:1>   config.mode = :block
irb(main):004:1> end
=> #<Obfuscate::Config:0x000055773ccbe9a0 @remove_trailing_equal=true, @encode=true, @mode=:block, @salt="User">
irb(main):005:0> Obfuscate.clarify(414)
Traceback (most recent call last):
        1: from (irb):5
NoMethodError (undefined method `%' for true:TrueClass)
irb(main):006:0> Obfuscate.clarify(1)
Traceback (most recent call last):
        1: from (irb):6
ArgumentError (invalid base64)
```

### Environment
- Ruby 2.5.3
- Rails 5.2.1

**Comment by mguymon** [comment]
So the blowfish impl is _really_ old,  so there is no way around that. This gem is old as well, might be a good idea to use a more secure gem for hiding ids. I would see if [JWT](https://github.com/jwt/ruby-jwt) or [Pasteo](https://github.com/paragonie/paseto) could fill the need.

I pushed a new gem 0.1.1 that will throw a `Obfuscate::Crypt::Base64Error` if it fails to decode the text, that should at least give you something to rescue on.

**Comment by yossy-ok** [comment]
Thank you for new gem.
I understand that I should `rescue` in everywhere when I use `clarify` (and `find_obfuscated` or something) at least.

I just noticed that the error occurs still now (and `ArgumentError (invalid base64)` occurs) in the new gem 0.1.1. `Obfuscate::Crypt::Base64Error` was not raised.

I don't care error classes in my use-cases, so following messages are what I just want to tell you.

---

I added error message logging for debug like following code, and I found out two reasons.

```ruby
# lib/obfuscate/crypt.rb
    if @exec_config.encode
      obfuscated << "=" if @exec_config.remove_trailing_equal?
      begin
              obfuscated = Base64.urlsafe_decode64(obfuscated)
      rescue => ex
        puts "========== message [1] ========="
        puts ex.message
        puts "================================"
        raise ex
      end
    end

    begin
      if @exec_config.mode == :string
        @crypt.decrypt_string(obfuscated)
      elsif @exec_config.mode == :block
        @crypt.decrypt_block(obfuscated).strip
      else
        raise UnsupportedModeError.new("Unknown mode: #{@exec_config.mode}")
      end
    rescue ArgumentError => ex
        puts "========== message [2] ========="
        puts ex.message
        puts "================================"
      raise Base64Error.new("Cannot decode #{text}") if ex.message == 'invalid base64'

      raise ex
    rescue => ex
        puts "========== message [3] ========="
        puts ex.message
        puts "================================"
      raise Base64Error.new("Cannot decode #{text}") if ex.message == "undefined method `%'"

      raise ex
    end
```

First reason is that error message is 'undefined method `%' for true:TrueClass', so `if ex.message == "undefined method `%'"` will be false in this case.

```
> Obfuscate.clarify(414)
========== message [3] =========
undefined method `%' for true:TrueClass
================================
Traceback (most recent call last):
        1: from (irb):5
NoMethodError (undefined method `%' for true:TrueClass)
```

Second one is that `ArgumentError (invalid base64)` occurs in `Base64.urlsafe_decode64`, so it doesn't reached to begin and rescue lines.

(The error occurred in and around `message [1]`)
```ruby
> Obfuscate.clarify(1)
========== message [1] =========
invalid base64
================================
Traceback (most recent call last):
        1: from (irb):6
ArgumentError (invalid base64)
```
https://github.com/mguymon/obfuscate/blob/master/lib/obfuscate/crypt.rb#L71

I appreciate your kindness, I really thank you.
